title: Manipulability Motion Control
description: Maximising Manipulability During Resolved-Rate Motion Control

github:
  repository_url: https://github.com/jhavl/ropy

google_analytics: UA-102222819-2

theme: jekyll-theme-cayman
