title: Manipulability Motion Control
description: A short description of your site's purpose

github:
  repository_url: https://github.com/jhavl/ropy

google_analytics: UA-102222819-2

theme: jekyll-theme-cayman
